/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamersRouteImport } from './routes/streamers'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as OrganizersRouteImport } from './routes/organizers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'

const StreamersRoute = StreamersRouteImport.update({
  id: '/streamers',
  path: '/streamers',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersRoute = OrganizersRouteImport.update({
  id: '/organizers',
  path: '/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/organizers': typeof OrganizersRoute
  '/schedule': typeof ScheduleRoute
  '/streamers': typeof StreamersRoute
  '/docs/$': typeof DocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/organizers': typeof OrganizersRoute
  '/schedule': typeof ScheduleRoute
  '/streamers': typeof StreamersRoute
  '/docs/$': typeof DocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/organizers': typeof OrganizersRoute
  '/schedule': typeof ScheduleRoute
  '/streamers': typeof StreamersRoute
  '/docs/$': typeof DocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/about'
    | '/organizers'
    | '/schedule'
    | '/streamers'
    | '/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/about'
    | '/organizers'
    | '/schedule'
    | '/streamers'
    | '/docs/$'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/about'
    | '/organizers'
    | '/schedule'
    | '/streamers'
    | '/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  OrganizersRoute: typeof OrganizersRoute
  ScheduleRoute: typeof ScheduleRoute
  StreamersRoute: typeof StreamersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/streamers': {
      id: '/streamers'
      path: '/streamers'
      fullPath: '/streamers'
      preLoaderRoute: typeof StreamersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers': {
      id: '/organizers'
      path: '/organizers'
      fullPath: '/organizers'
      preLoaderRoute: typeof OrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  OrganizersRoute: OrganizersRoute,
  ScheduleRoute: ScheduleRoute,
  StreamersRoute: StreamersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
